language: python
python:
  - "3.6.4"
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - pytest --cov=apiv2 apiv2/models/tests/
  - coverage run -m unittest discover tests/
  - coverage report
after_success:
  - coveralls
notifications:
  email: false