language: python
python:
  - "3.6.4"
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - coverage run -m unittest discover ./tests
  - coverage report
after_success:
  - coveralls
notifications:
  email: false